### ISSUE TITLE
Create Helm charts for regtech-mail-api and mailpit

### ISSUE THREAD

**Issue by hkeeler** [cfpb/regtech-mail-api#5]
We obviously need a Helm chart for the Mail API. It should be very similar to to our other FastAPI-based repos. One fun bit will be setting up the Secrets to pull in the SMTP credentials. We're not going to know if the TLS setup is correct until we test it on-cluster. This _may_ mean having to tweak the underlying Python SMTP code if it doesn't.

We probably also want a chart for [mailpit](https://mailpit.axllent.org/docs/install/). There is a chart out on ArtifactHub that looks decent (https://artifacthub.io/packages/helm/jouve/mailpit), but it is not from the mailpit dev, so we should do a little digging there to see if we want to go that route or create our own.

**Comment by jcadam14** [comment]
Going to write stories for this in the EKS and regtech-deployment repos for the values and charts, respectively.  Will leave this here in case there are any changes needed to this source to support those.
