### ISSUE TITLE
Finalize `POST /send` response message structure

### ISSUE THREAD

**Issue by hkeeler** [cfpb/regtech-mail-api#9]
The initial version of the `POST /send` endpoint looks like:

```json
{
  "email": {
    "subject": "Institution Profile Change",
    "body": "lei: 1234567890ABCDEFGHIJ\ninstitution_name_1: Fintech 1\ntin_1: 12-3456789\nrssd_1: 1234567",
    "from_addr": "noreply@localhost.localdomain",
    "sender": "Jane Doe <jane.doe@some.org>",
    "to": [
      "cases@localhost.localdomain"
    ],
    "cc": null,
    "bcc": null
  }
}
```

This was just an off-the-cuff first stab at this. Let's come to an agreement on what's actually useful to a client of this service, also taking into account that we don't want to leak any unnecessary data.

**Comment by jcadam14** [comment]
Think we're good here
